### ISSUE TITLE
the fog

### ISSUE THREAD

**Issue by Spritzerland** [MercuryWorkshop/halcyon-website#2]
the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog

**Comment by velzie** [comment]
the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog the fog
